name: Deploy to IIS Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Restore NuGet Packages
      - name: Restore NuGet Packages
        run: |
          nuget restore RescueRide.sln

      # Step 3: Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Step 4: Build the Project
      - name: Build Project
        run: |
          msbuild RescueRide.sln /p:Configuration=Release

      # Step 5: Install Web Deploy
      - name: Install Web Deploy
        run: |
          choco install webdeploy -y

      # Step 6: Deploy to IIS Server using Web Deploy
      - name: Deploy to IIS Server
        shell: pwsh
        run: |
          & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:contentPath="./bin/Release" `
            -dest:auto,computerName="${{ secrets.DEPLOY_SERVER }}",userName="${{ secrets.DEPLOY_USERNAME }}",password="${{ secrets.DEPLOY_PASSWORD }}",includeAcls="False" `
            -allowUntrusted `
            -siteName="${{ secrets.DEPLOY_SITE }}"
