name: Deploy to IIS Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Restore NuGet packages
      - name: Restore NuGet Packages
        run: |
          nuget restore RescueRide.sln

      # Step 3: Build the project
      - name: Build Project
        run: |
          msbuild RescueRide.sln /p:Configuration=Release

      # Step 4: Deploy to IIS Server using Web Deploy
      - name: Deploy to IIS Server
        run: |
          msdeploy.exe -source:contentPath="./bin/Release" ^
                       -dest:auto,computerName="${{ secrets.DEPLOY_SERVER }}",userName="${{ secrets.DEPLOY_USERNAME }}",password="${{ secrets.DEPLOY_PASSWORD }}
